language: scala

scala:
   - 2.11.7

jdk:
  - oraclejdk7

env:
  - IDEA_VERSION=IC-15.0.2
  - IDEA_VERSION=IU-15.0.2
  - RUN_WITH_PYTHON=true
  - RUN_WITH_PYTHON=false

script:
  - ./gradlew --console plain check
